In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({
    'color': ['red','blue','green','red','blue','green'],
    'size': ['Small','Medium','Large','Medium','Small','Large']
})

df

   color    size
0    red   Small
1   blue  Medium
2  green   Large
3    red  Medium
4   blue   Small
5  green   Large

In [5]:
le_color = LabelEncoder()
le_size = LabelEncoder()

df['color_label'] = le_color.fit_transform(df['color'])
df['size_label'] = le_size.fit_transform(df['size'])

df

   color    size  color_label  size_label
0    red   Small            2           2
1   blue  Medium            0           1
2  green   Large            1           0
3    red  Medium            2           1
4   blue   Small            0           2
5  green   Large            1           0

In [7]:
oe = OrdinalEncoder(categories=[['Small','Medium','Large']])

df['size_ordinal'] = oe.fit_transform(df[['size']])

df

   color    size  color_label  size_label  size_encoded  size_ordinal
0    red   Small            2           2           0.0           0.0
1   blue  Medium            0           1           1.0           1.0
2  green   Large            1           0           2.0           2.0
3    red  Medium            2           1           1.0           1.0
4   blue   Small            0           2           0.0           0.0
5  green   Large            1           0           2.0           2.0